V1/ATP2.BDAID/ATP2.BDAID.Web/Controllers/HostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATP2.BDAID.Entities;
using ATP2.BDAID.Framework.Constant;
using ATP2.BDAID.Framework.Helper;
using ATP2.BDAID.Web.Framework.Attributes;
using ATP2.BDAID.Web.Framework.Base;

namespace ATP2.BDAID.Web.Controllers
{
    [BDAIDAuthorize(EnumCollection.UserType.Admin)]

    public class HostController : BaseController
    {
        //
        // GET: /RegisteredUser/Host/
        public ActionResult Index()
        {
            var userinfo = userInfoService.GetAll();
            return View(userinfo);
        }

        public ActionResult DetailView()
        {
            var userinfo = new UserInfo();
            return View(userinfo);
        }
        public ActionResult Save(int id)
        {
            var user = userInfoService.GetByID(id).Data;
            return View("DetailView", user);

        }
        [HttpPost]
        public ActionResult Save(UserInfo userinfo)
        {
            if (!ModelState.IsValid)
            {
                return View("DetailView",userinfo);
            }

            try
            {
                var result = userInfoService.Save(userinfo);
                if (result.HasError)
                {
                    ViewBag.Message = result.Message;
                    return View("DetailView", userinfo);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            userInfoService.Delete(id);
            return RedirectToAction("Index");
        }
	}
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Views/Host/DetailView.cshtml
@model ATP2.BDAID.Entities.UserInfo
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_AuthorizeLayout.cshtml";
}
<h2>@ViewBag.Message</h2>

@if (Model.ID == 0)
{
    <h2>Add User Info</h2>
}
else
{
    <h2>Edit User Info</h2>
}

@using (Html.BeginForm("Save", "Host"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Username)
        @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Username)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Email)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password)
        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Password)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Contact)
        @Html.TextBoxFor(m => m.Contact, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Contact)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.UsertypeID)
        @Html.TextBoxFor(m => m.UsertypeID, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.UsertypeID)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Gender)
        @Html.TextBoxFor(m => m.Gender, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Gender)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Age)
        @Html.TextBoxFor(m => m.Age, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Age)
    </div>
    <br />
    <button type="submit" class="btn btn-info">Save</button>
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Views/Host/Index.cshtml
          
@model List<ATP2.BDAID.Entities.UserInfo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AuthorizeLayout.cshtml";
}

<h2>Index</h2>
@using (Html.BeginForm( "DetailView","Host"))
{
    <table class="table table-bordered table-striped">
        <tr>
            <td>
                ID
            </td>
            <td>
                Name
            </td>
            <td>
                User Name
            </td>
            <td>
                Email
            </td>
            <td>
                Password
            </td>
            <td>
                Contact
            </td>
            <td>
                UserType
            </td>
            <td>
               Gender
            </td>
            <td>
                Age
            </td>

        </tr>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    @user.ID
                </td>
                <td>
                    @user.Name
                </td>
                <td>
                    @user.Username
                </td>
                <td>
                    @user.Email
                </td>
                <td>
                    @user.Password
                </td>
                <td>
                    @user.Contact
                </td>
                <td>
                    @user.UsertypeID
                </td>
                <td>
                    @user.Gender
                </td>
                <td>
                    @user.Age
                </td>
                <td>
                    @Html.ActionLink("Edit", "Save", new { Controller = "Host", id = user.ID })
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { Controller = "Host", id = user.ID })
                </td>
            </tr>
        }

    </table>
    <button type="submit" class="btn btn-info">ADD</button>

}