V1/ATP2.BDAID/ATP2.BDAID.Web/Controllers/AdminEmployeeController.cs
using System;
using System.Web.Mvc;
using ATP2.BDAID.Entities;
using ATP2.BDAID.Framework.Constant;
using ATP2.BDAID.Framework.Helper;
using ATP2.BDAID.Model.Admin;
using ATP2.BDAID.Services.Admin;
using ATP2.BDAID.Web.Framework.Base;

namespace ATP2.BDAID.Web.Controllers
{
    public class AdminEmployeeController : BaseController
    {
        //
        // GET: /AdminEmployee/
        public ActionResult List(string key="")
        {
            var model = EmployeeService.GetAll(key);

            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"];
            }

            if (TempData["Success"] != null)
            {
                ViewBag.Success = TempData["Success"];
            }

            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var result = EmployeeService.GetByID(id);
            var model = new EmployeeModel()
            {
                Employee = result.Data??new Employee(){UserInfo = new UserInfo(){Password = "1"}},
                Statuses = EnumCollection.GetUserStatusEnum()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Detail(Employee employee)
        {
            if (!ModelState.IsValid)
            {
                var model = new EmployeeModel()
                {
                    Employee = employee,
                    Statuses = EnumCollection.GetUserStatusEnum()
                };

                return View(model);
            }

            bool isPass = false;
            employee.UserInfo.UserTypeID = (int) EnumCollection.UserTypeEnum.Employee;
            if (employee.UserInfo.Password=="1")
            {
                employee.UserInfo.Password = new Random().Next(11111, 99999).ToString();
                isPass = true;
            }

            var result = EmployeeService.Save(employee);

            if (result.HasError)
            {
                ViewBag.Error = result.Message;
                var model = new EmployeeModel()
                {
                    Employee = employee,
                    Statuses = EnumCollection.GetUserStatusEnum()
                };
                return View(model);
            }

            if (isPass)
            {
                TempData["Success"] = result.Data.UserInfo.Email + ",Your Password is " + result.Data.UserInfo.Password;
            }

            return RedirectToAction("List");
        }
	}
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Controllers/AdminHostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATP2.BDAID.Entities;
using ATP2.BDAID.Framework.Constant;
using ATP2.BDAID.Framework.Helper;
using ATP2.BDAID.Web.Framework.Attributes;
using ATP2.BDAID.Web.Framework.Base;
using ATP2.BDAID.Web.Framework.Util;

namespace ATP2.BDAID.Web.Controllers
{
    [BDAIDAuthorize(new int[] { (int)EnumCollection.UserTypeEnum.Admin, (int)EnumCollection.UserTypeEnum.Employee })]
    public class AdminHostController : BaseController
    {
        //
        // GET: /RegisteredUser/Host/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Profile()
        {
            return View(HttpUtil.UserProfile);
        }

        public ActionResult DashBoard()
        {

            return View();
        }
	}
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Controllers/AdminPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATP2.BDAID.Entities;
using ATP2.BDAID.Services.Admin;
using ATP2.BDAID.Web.Framework.Base;

namespace ATP2.BDAID.Web.Controllers
{
    public class AdminPostController : BaseController
    {
        // GET: AdminUser
        public ActionResult List()
        {
            return View();
        }

        public ActionResult Detail(int id)
        {
            ViewBag.ID = id;
            return View();
        }
    }
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Controllers/AdminServiceController.cs
using System.Web.Mvc;
using ATP2.BDAID.Entities;
using ATP2.BDAID.Framework.Constant;
using ATP2.BDAID.Model.Admin;
using ATP2.BDAID.Services.Admin;
using ATP2.BDAID.Web.Framework.Base;

namespace ATP2.BDAID.Web.Controllers
{
    public class AdminServiceController : BaseController
    {
        //
        // GET: /AdminService/
        public ActionResult List()
        {
            var model = ServiceTypeService.GetAll();

            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"];
            }

            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var result = ServiceTypeService.GetByID(id);
            var model = new ServiceModel()
            {
                Service = result.Data??new Service(),
                ServiceTypes = EnumCollection.GetServiceTypeEnum()
            };

            return View(model);
        }

        public ActionResult Reports()
        {
            var result = ServiceAuditService.GetAll();

            return View(result);
        }

        [HttpPost]
        public ActionResult Detail(Service service)
        {
            if (!ModelState.IsValid)
            {
                var model = new ServiceModel()
                {
                    Service = service,
                    ServiceTypes = EnumCollection.GetServiceTypeEnum()
                };

                return View(model);
            }
            var result = ServiceTypeService.Save(service);

            if (result.HasError)
            {
                ViewBag.Error = result.Message;
                var model = new ServiceModel()
                {
                    Service = service,
                    ServiceTypes = EnumCollection.GetServiceTypeEnum()
                };
                return View(model);
            }

            return RedirectToAction("List");
        }

        public ActionResult Delete(int id)
        {
            var result = ServiceTypeService.Delete(id);

            if (!result)
            {
                TempData["Error"] = "Something went wrong";
            }
             return RedirectToAction("List");
        }
	}
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATP2.BDAID.Entities;
using ATP2.BDAID.Model.Admin;
using ATP2.BDAID.Services.Admin;
using ATP2.BDAID.Web.Framework.Base;

namespace ATP2.BDAID.Web.Controllers
{
    public class AdminUserController : BaseController
    {
        // GET: AdminUser
        public ActionResult List(string key="")
        {
            var model = Reg_UserService.GetAll(key);

            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"];
            }

            return View(model);
        }

        public ActionResult Detail(int id)
        {

            var result = Reg_UserService.GetByID(id);

            if (result.HasError)
            {
                TempData["Error"] = result.Message;
                return RedirectToAction("List");
            }

            var model = new UserModel()
            {
                User = result.Data,
                Posts = PostService.GetAllByUserId(result.Data.UserInfo.ID)
            };
            return View(model);
        }

        public ActionResult UpdateStatus(int id)
        {
            var result = Reg_UserService.UpdateStatus(id);

            if (result.HasError)
            {
                TempData["Error"] = result.Message;
            }

            return RedirectToAction("List");
        }
        
    }
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Views/AdminHost/DashBoard.cshtml

@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_InnerLayout.cshtml";
}

<div class="row" ng-controller="DashboardController" ng-init="Init('@Url.Content("~/")')" align="center">
    <table style="width: 90%">
        <tr>
            <td style="width: 45%">
                <div class="panel panel-default">
                    <div class="panel-heading">Posts</div>
                    <div class="panel-body">
                        <canvas id="pie" class="chart chart-pie"
                                chart-data="dataPosts" chart-labels="labelPosts" chart-options="options"></canvas>
                    </div>
                </div>
            </td>
            <td style="width: 10%">&nbsp;</td>
            <td style="width: 45%">
                <div class="panel panel-default">
                    <div class="panel-heading">Weekly Responses</div>
                    <div class="panel-body" style="background-color: white">
                        <canvas id="pie" class="chart chart-line"
                                chart-data="data1" chart-labels="labels1" chart-options="options"></canvas>
                    </div>
                </div>
            </td>
        </tr>
        @*<tr><td>&nbsp;</td></tr>*@
        @*<tr>
            <td colspan="3">
                <div class="panel panel-default">
                    <div class="panel-heading">Users</div>
                    <div class="panel-body" style="background-color: white">
                        <canvas id="pie" class="chart chart-bar"
                                chart-data="dataUsers" chart-labels="labelUsers" chart-options="options"></canvas>
                    </div>
                </div>
                
            </td>
        </tr>*@
    </table>
</div>


V1/ATP2.BDAID/ATP2.BDAID.Web/Views/AdminHost/Index.cshtml
@using ATP2.BDAID.Framework.Constant
@using ATP2.BDAID.Web.Framework.Util
@model List<ATP2.BDAID.Entities.UserInfo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AuthorizeLayout.cshtml";
}

<div class="row" style="margin-top: 10px">
    <div class="col-md-3">
        <div class="list-group">
            <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Profile","AdminHost")','Profile')">Profile</a>
            <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("List","AdminService")', 'Services')">Services</a>
            @if (HttpUtil.UserProfile.UserTypeID == (int)EnumCollection.UserTypeEnum.Admin)
            {
                <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("List","AdminEmployee")','Employees')">Employees</a>
            }
            <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("List", "AdminUser")','Users')">Users</a>
            <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("List","AdminPost")','Posts')">Posts</a>
            @*<a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("MessageIndex","RegisteredHost")','Message')">Message Box</a>*@
        </div>
    </div>
    <div class="col-md-9">
        <ul class="nav nav-tabs" role="tablist" id="tabBar">
            <li role="presentation" id="liDash" class="active"><a href="#dashboard" aria-controls="home" role="tab" data-toggle="tab">Dashboard</a></li>
            <li role="presentation" id="liContainer"><a href="#postContainer" id="hContainer" aria-controls="home" role="tab" data-toggle="tab">Profile</a></li>
        </ul>
        <div class="tab-content" id="tabContainer">
            <div role="tabpanel" class="tab-pane active" id="dashboard">
                <iframe id="iDashBoard" src="@Url.Action("DashBoard","AdminHost")" width="100%" frameborder="0"></iframe>
            </div>
            <div role="tabpanel" class="tab-pane" id="postContainer">
                <iframe id="iFrameContainer" src="@Url.Action("Profile","AdminHost")" width="100%" frameborder="0"></iframe>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>

        $(document).ready(function () {

            var height = $(document).height() - 135;
            $("#iFrameContainer").height(height);
            $("#iDashBoard").height(height);
        });

        function ChangeIframe(url, tablName) {
            $('#hContainer').text(tablName);

            $("#iFrameContainer").attr('src', url);

            $('#liDash').removeClass('active');
            $('#dashboard').removeClass('active');
            $('#liContainer').addClass('active');
            $('#postContainer').addClass('active');

        }

    </script>
}


V1/ATP2.BDAID/ATP2.BDAID.Web/Views/AdminHost/Profile.cshtml
@using ATP2.BDAID.Framework.Constant
@model ATP2.BDAID.Framework.Object.UserProfile
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_InnerLayout.cshtml";
}

<h2>Profile</h2>
<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>@Model.ID</td>
        <td>Name</td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>@Model.Email</td>
        <td>User Type</td>
        <td>@((EnumCollection.UserTypeEnum)Model.UserTypeID)</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>Active</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>

</table>
