V1/ATP2.BDAID/ATP2.BDAID.Web/Controllers/RegisteredHostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATP2.BDAID.Entities;
using ATP2.BDAID.Framework.Constant;
using ATP2.BDAID.Framework.Helper;
using ATP2.BDAID.Web.Framework.Attributes;
using ATP2.BDAID.Web.Framework.Base;
using ATP2.BDAID.Web.Framework.Util;

namespace ATP2.BDAID.Web.Controllers
{
    [BDAIDAuthorize(new int[] { (int)EnumCollection.UserTypeEnum.RegisteredUser, (int)EnumCollection.UserTypeEnum.NonRegisteredUser })]
    public class RegisteredHostController : BaseController
    {
        //
        // GET: /RegisteredUser/Host/
        public ActionResult Index(int id=-1)
        {
            if (id == -1)
                id = 1;

            ViewBag.ID = id;
            ViewBag.Services = ServiceTypeService.GetAll();
            return View();
        }

        public ActionResult Index2(int id = -1)
        {
            if (id == -1)
                id = 1;

            ViewBag.ID = id;
            ViewBag.Services = ServiceTypeService.GetAll();
            return View();
        }

        public ActionResult Profile()
        {
            var result = Reg_UserService.GetByID(HttpUtil.UserProfile.ID);
            var model = result.Data ?? new Reg_User() {UserInfo = new UserInfo()};
            return View(model);
        }

        public ActionResult EditProfile()
        {
            var model = new Reg_User(){ID = HttpUtil.UserProfile.ID,DOB = DateTime.Now};
            return View(model);
        }

        [HttpPost]
        public ActionResult EditProfile(Reg_User model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = Reg_UserService.Save(model);

            if (result.HasError)
            {
                ViewBag.Message = result.Message;
                return View(model);
            }

            return RedirectToAction("Profile");
        }

        public ActionResult DashBoard()
        {
            return View();
        }

        public ActionResult MessageIndex()
        {
            return View();
        }
	}
}

V1/ATP2.BDAID/ATP2.BDAID.Web/Views/RegisteredHost/DashBoard.cshtml

@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_InnerLayout.cshtml";
}

<div class="row" ng-controller="RDashboardController" ng-init="Init('@Url.Content("~/")')" align="center">
    <table style="width: 90%">
        <tr>
            <td style="width: 45%">
                <div class="panel panel-default">
                    <div class="panel-heading">All User Posts</div>
                    <div class="panel-body">
                        <canvas id="pie" class="chart chart-pie"
                                chart-data="dataPosts" chart-labels="labelPosts" chart-options="options"></canvas>
                    </div>
                </div>
            </td>
            <td style="width: 10%">&nbsp;</td>
            <td style="width: 45%">
                <div class="panel panel-default">
                    <div class="panel-heading">Personal Posts</div>
                    <div class="panel-body" style="background-color: white">
                        <canvas id="pie" class="chart chart-pie"
                                chart-data="dataCurrentPosts" chart-labels="labelCurrentPosts" chart-options="options"></canvas>
                    </div>
                </div>
            </td>
        </tr>
        <tr><td>&nbsp;</td></tr>
    </table>
</div>


V1/ATP2.BDAID/ATP2.BDAID.Web/Views/RegisteredHost/EditProfile.cshtml
@model ATP2.BDAID.Entities.Reg_User
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_InnerLayout.cshtml";
}
@using (Html.BeginForm("EditProfile"))
{
    <br />
    if (!string.IsNullOrEmpty(ViewBag.Message))
    {
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Oh snap!</strong> @ViewBag.Message
        </div>
        <br />
    }

    <button type="submit" class="btn btn-info btn-sm">Save</button><br /><br />
    <table class="table table-striped table-hover">
        <tr>
            <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> @Html.LabelFor(m => m.ID) </td>
            <td>
                @Html.TextBoxFor(m => m.ID, new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(m => m.ID)
            </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> @Html.LabelFor(m => m.DOB) </td>
            <td>
                @Html.TextBoxFor(m => m.DOB, new { @class = "form-control", type = "date" })
                @Html.ValidationMessageFor(m => m.DOB)
            </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> @Html.LabelFor(m => m.Gender) </td>
            <td>
                @Html.RadioButtonFor(m => m.Gender, "Male")&nbsp;Male &nbsp;&nbsp;
                @Html.RadioButtonFor(m => m.Gender, "Female")&nbsp;Female
                @Html.ValidationMessageFor(m => m.Gender)
            </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> @Html.LabelFor(m => m.Contact) </td>
            <td>
                @Html.TextBoxFor(m => m.Contact, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Contact)
            </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> @Html.LabelFor(m => m.Profession) </td>
            <td>
                @Html.TextBoxFor(m => m.Profession, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Profession)
            </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> @Html.LabelFor(m => m.Address) </td>
            <td>
                @Html.TextAreaFor(m => m.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Address)
            </td>
        </tr>

    </table>
}



V1/ATP2.BDAID/ATP2.BDAID.Web/Views/RegisteredHost/Index.cshtml
@using ATP2.BDAID.Entities
@using ATP2.BDAID.Framework.Constant
@using ATP2.BDAID.Web.Framework.Util
@model List<ATP2.BDAID.Entities.UserInfo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_RUAuthorizeLayout.cshtml";
    var services = (List<Service>) ViewBag.Services;
    int tid = (int) ViewBag.ID;
    string mClass = tid == 1 ? "active" : "";
    string cClass = tid == 2 ? "active" : "";
}

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index","RegisteredHost")">BDAid</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#" onclick="ChangeIframe('@Url.Action("Index","RegisteredPost",new{sid=-1})','Home')">Home</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        @foreach (var service in services)
                        {
                            <li>
                                <a href="#" onclick="ChangeIframe('@Url.Action("Index","RegisteredPost",new{sid=service.ID})','@service.Name')">@service.Name</a>
                            </li>
                        }
                    </ul>
                </li>
                <li class="@mClass"><a href="@Url.Action("Index","RegisteredHost",new{id=1})">Mugger</a></li>
                <li class="@cClass"><a href="@Url.Action("Index","RegisteredHost",new{id=2})">Collaborator</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li> @Html.ActionLink("Welcome, " + HttpUtil.UserProfile.Name, "Index", "RegisteredHost")</li>
                <li> @Html.ActionLink("Log Out", "Logout", "Account")</li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid body-content">
    <div class="row" style="margin-top: 10px">
        <div class="col-md-3">
            <div class="list-group">
                <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Profile","RegisteredHost")','Profile')">Profile</a>
                @if (tid == 1)
                {
                    <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("NewPost", "RegisteredPost")','Post')">Post</a>
    <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Response", "RegisteredPost")','Responses')">Response</a>
                }

                @*<a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("NewPost", "RegisteredPost")','Post')">Post</a>*@
                @if (tid == 2)
                {
                    <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Donations","RegisteredPost")', 'Donations')">Donations</a>
                }

                <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("MessageIndex","RegisteredHost")','Message')">Message Box</a>
            </div>
        </div>
        <div class="col-md-9">
            <ul class="nav nav-tabs" role="tablist" id="tabBar">
                <li role="presentation" id="liDash" class="active"><a href="#dashboard" aria-controls="home" role="tab" data-toggle="tab">Dashboard</a></li>
                <li role="presentation" id="liContainer"><a href="#postContainer" id="hContainer" aria-controls="home" role="tab" data-toggle="tab">Profile</a></li>
            </ul>
            <div class="tab-content" id="tabContainer">
                <div role="tabpanel" class="tab-pane active" id="dashboard">
                    <iframe id="iDashBoard" src="@Url.Action("DashBoard","RegisteredHost")" width="100%" frameborder="0"></iframe>
                </div>
                <div role="tabpanel" class="tab-pane" id="postContainer">
                    <iframe id="iFrameContainer" src="@Url.Action("Profile", "RegisteredHost")" width="100%" frameborder="0"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script>

        $(document).ready(function () {

            var height = $(document).height() - 135;
            $("#iFrameContainer").height(height);
            $("#iDashBoard").height(height);
        });

        function ChangeIframe(url, tablName) {
            $('#hContainer').text(tablName);

            $("#iFrameContainer").attr('src', url);

            $('#liDash').removeClass('active');
            $('#dashboard').removeClass('active');
            $('#liContainer').addClass('active');
            $('#postContainer').addClass('active');

        }

    </script>
}


V1/ATP2.BDAID/ATP2.BDAID.Web/Views/RegisteredHost/Index2.cshtml
@using ATP2.BDAID.Entities
@using ATP2.BDAID.Framework.Constant
@using ATP2.BDAID.Web.Framework.Util
@model List<ATP2.BDAID.Entities.UserInfo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_RUAuthorizeLayout.cshtml";
    var services = (List<Service>) ViewBag.Services;
    int tid = (int) ViewBag.ID;
}

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index2","RegisteredHost")">BDAid</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#" onclick="ChangeIframe('@Url.Action("Index","RegisteredPost",new{sid=-1})','Home')">Home</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        @foreach (var service in services)
                        {
                            <li>
                                <a href="#" onclick="ChangeIframe('@Url.Action("Index","RegisteredPost",new{sid=service.ID})','@service.Name')">@service.Name</a>
                            </li>
                        }
                    </ul>
                </li>
                <li><a href="@Url.Action("Index2","RegisteredHost",new{id=1})">Mugger</a></li>
                <li><a href="@Url.Action("Index2","RegisteredHost",new{id=2})">Collaborator</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li> @Html.ActionLink("Welcome, " + HttpUtil.UserProfile.Name, "Index", "RegisteredHost")</li>
                <li> @Html.ActionLink("Log Out", "Logout", "Account")</li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid body-content">
    <div class="row" style="margin-top: 10px">
        <div class="col-md-3">
            <div class="list-group">
                <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Profile","RegisteredHost")','Profile')">Profile</a>
                @if (tid == 1)
                {
                    <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("NewPost", "RegisteredPost")','Post')">Post</a>
                    <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Response", "RegisteredPost")','Responses')">Response</a>
                }

                @*<a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("NewPost", "RegisteredPost")','Post')">Post</a>*@
                @if (tid == 2)
                {
                    <a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Donations","RegisteredPost")', 'Donations')">Donations</a>
                }

                @*<a class="list-group-item" href="#" onclick="ChangeIframe('@Url.Action("Profile","Adminhost")','Message')">Message Box</a>*@
            </div>
        </div>
        <div class="col-md-9">
            <ul class="nav nav-tabs" role="tablist" id="tabBar">
                
                <li role="presentation" id="liContainer" class="active"><a href="#postContainer" id="hContainer" aria-controls="home" role="tab" data-toggle="tab">Profile</a></li>
            </ul>
            <div class="tab-content" id="tabContainer">
                <div role="tabpanel" class="tab-pane active" id="postContainer">
                    <iframe id="iFrameContainer" src="@Url.Action("Profile", "RegisteredHost")" width="100%" frameborder="0"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script>

        $(document).ready(function () {

            var height = $(document).height() - 135;
            $("#iFrameContainer").height(height);
            $("#iDashBoard").height(height);
        });

        function ChangeIframe(url, tablName) {
            $('#hContainer').text(tablName);

            $("#iFrameContainer").attr('src', url);

            $('#liDash').removeClass('active');
            $('#dashboard').removeClass('active');
            $('#liContainer').addClass('active');
            $('#postContainer').addClass('active');

        }

    </script>
}


V1/ATP2.BDAID/ATP2.BDAID.Web/Views/RegisteredHost/MessageIndex.cshtml
@using ATP2.BDAID.Web.Framework.Util

@{
    ViewBag.Title = "MessageIndex";
    Layout = "~/Views/Shared/_InnerLayout.cshtml";
}

<br/>
<div class="row" ng-controller="MessageController" ng-init="Init('@Url.Content("~/")','@HttpUtil.UserProfile.Email')">
    <div ng-show="ProcessingCount>0">
        Loading....
    </div>
    <div class="col-md-3" style="overflow-y: auto;border: 1px solid darkgray;height: 470px">
        <table class="table table-hover" style="width: 100%">
            <tr ng-repeat="user in UserList" ng-click="ChangeRow($index)" ng-class="{'selectedRow': $index == SelectedIndex}" style="cursor: pointer">
                <td>
                    <b>{{user.Name}}</b><br />
                    {{user.Email}}
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-9" style="overflow-y: auto;border: 1px solid darkgray;height: 470px">
        <table class="table table-striped" style="width: 100%">
            <tr ng-repeat="message in MessageList" ng-show="MessageList.length>0">
                <td style="width: 15%">
                    <b ng-show="message.ReceiverEmail==CurrentUser">{{message.SenderEmail}}</b>
                </td>
                <td style="width: 70%">
                    <p ng-show="message.SenderEmail==CurrentUser" class="text-right">
                        {{message.Messages}}
                        <br />
                        <small>{{message.Duration}}</small>
                    </p>
                    <p ng-show="message.ReceiverEmail==CurrentUser" class="text-left">
                        {{message.Messages}}
                        <br />
                        <small>{{message.Duration}}</small>
                    </p>
                </td>
                <td style="width: 15%">
                    <b ng-show="message.SenderEmail==CurrentUser">You</b>
                </td>
            </tr>
            <tr ng-show="SelectedIndex!=-1">
                <td style="width: 15%">
                    Message
                </td>
                <td colspan="2">
                    <textarea class="form-control" placeholder="Message" ng-model="messages"></textarea>
                    <input type="button" class="btn btn-info btn-sm" value="Send" ng-click="Send()" />
                </td>
            </tr>
        </table>
    </div>
</div>

<style>
    .selectedRow {
        background-color: gray;
    }
</style>




V1/ATP2.BDAID/ATP2.BDAID.Web/Views/RegisteredHost/Profile.cshtml
@using ATP2.BDAID.Framework.Constant
@model ATP2.BDAID.Entities.Reg_User
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_InnerLayout.cshtml";
}
<br />
@if (Model.UserInfo.UserTypeID == (int)EnumCollection.UserTypeEnum.RegisteredUser && Model.DOB==DateTime.MinValue)
{
    <h4 style="color:red">For using this site properly You need to fill up the required information and Editing progress should be 100% </h4>
    <h3>Editing Progress </h3>
    <div class="row">
        <div class="col-md-9">
            <div id="myProgress">
                <div id="myBar">50%</div>
            </div>
        </div>
        <div class="col-md-3">
            <a class="btn btn-info form-control" href="@Url.Action("EditProfile","RegisteredHost")">Update Profile</a>
        </div>
    </div>
}
<br />
<div class="card">

    <h1><span class="glyphicon glyphicon-user" aria-hidden="true"> &nbsp; </span>  @Model.UserInfo.Name </h1>
    @if (Model.DOB != DateTime.MinValue)
    {
        <p class="title"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"> &nbsp; </span> @Model.Profession</p>
        <p><span class="glyphicon glyphicon-earphone" aria-hidden="true"> &nbsp; </span> @Model.Contact</p>
    }


</div>
<br />
<table class="table table-striped table-hover">
    <tr>
        <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> ID </td>
        <td>@Model.UserInfo.ID</td>
    </tr>
    <tr>
        <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> Name </td>
        <td>@Model.UserInfo.Name</td>
    </tr>
    <tr>
        <td><span class="glyphicon glyphicon-envelope" aria-hidden="true"> &nbsp; </span> Email </td>
        <td>@Model.UserInfo.Email</td>
    </tr>
    @if (Model.DOB != DateTime.MinValue)
    {
        <tr>
            <td><span class="glyphicon glyphicon-envelope" aria-hidden="true"> &nbsp; </span> Gender </td>
            <td>@Model.Gender</td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-envelope" aria-hidden="true"> &nbsp; </span> DOB </td>
            <td>@Model.DOB.ToShortDateString()</td>
        </tr>
    }
    <tr>
        <td><span class="glyphicon glyphicon-tasks" aria-hidden="true"> &nbsp; </span> User Type </td>
        <td>@((EnumCollection.UserTypeEnum)Model.UserInfo.UserTypeID)</td>
        <td></td>
    </tr>

</table>




<style>
    .card {
        box-shadow: 0 -8px -16px -16px #7A7676;
        max-width: 800px;
        margin: auto;
        text-align: center;
        font-family: arial;
    }

    .title {
        color: grey;
        font-size: 18px;
    }

    button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

    .bt {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #615F5F;
        text-align: center;
        cursor: pointer;
        width: 25%;
        font-size: 18px;
    }

    a {
        text-decoration: none;
        font-size: 22px;
        color: black;
    }

        button:hover, a:hover {
            opacity: 0.7;
        }

    #t2 {
        -moz-tab-size: 16; /* Firefox */
        -o-tab-size: 16; /* Opera 10.6-12.1 */
        tab-size: 16;
    }

    #myProgress {
        width: 100%;
        background-color: #ddd;
    }

    #myBar {
        width: 50%;
        height: 30px;
        background-color: #4CAF50;
        text-align: center;
        line-height: 30px;
        color: white;
    }
</style>